p <- 'step2/plots/'
read <- function(name) read.delim(paste0(p,name))
png(paste0(p,'01_family_and_haplotype_distribution.png'),width=2400,height=1800,res=180)
par(mfrow=c(2,2),mar=c(4.5,5,3,1),oma=c(3,0,3,0))
d<-read('family_scatter.tsv')
plot(d[[1]],d[[2]],pch=16,cex=.18,col=adjustcolor(ifelse(d$pooled_pass==1,'#247BA0','#E49A32'),alpha.f=.18),xlab='log10(HSat2 density + 1e-9)',ylab='log10(HSat3 density + 1e-9)',main='Family density (573 haplotypes pooled)');abline(0,1,col='gray50',lty=2)
legend('topleft',c('Pooled E > 10','Local-only E > 10'),col=c('#247BA0','#E49A32'),pch=16,bty='n')
d<-read('family_share_hist.tsv');plot(d$midpoint,d$count,type='h',lwd=12,col='#268878',xlab='HSat2 / (HSat2 + HSat3) count fraction',ylab='Candidates',main='Family count preference',ylim=c(0,max(d$count)*1.1))
d<-read('prevalence_hist.tsv');plot(d$midpoint*100,d$count,type='h',lwd=12,col='#247BA0',xlab='Haplotypes with union target occurrence (%)',ylab='Candidates',main='Haplotype prevalence',ylim=c(0,max(d$count)*1.1))
d<-read('union_chr_share_hist.tsv');plot(d$midpoint,d$count,type='h',lwd=12,col='#E49A32',xlab='Largest chromosome / union total count',ylab='Candidates',main='Chromosome count concentration',ylim=c(0,max(d$count)*1.1))
mtext('STEP 2 | Family and haplotype distribution',outer=TRUE,side=3,line=1,font=2,cex=1.4)
mtext('159,988 candidates; CHM13 excluded from pooled summaries. Exact canonical 16-mer counts.',outer=TRUE,side=1,line=.5,cex=.85)
mtext('Counts and prevalence are conditional on available T2T-passed chromosomes. HSat2/3 union includes family-boundary windows.',outer=TRUE,side=1,line=1.7,cex=.75)
dev.off()

d<-read('chromosome_heatmap.tsv');labels<-d[[1]];mat<-as.matrix(d[,-1]);display<-mat[nrow(mat):1,,drop=FALSE]
png(paste0(p,'02_chromosome_density_heatmap.png'),width=2400,height=2000,res=180)
par(mar=c(5,8,5,3))
image(seq_len(ncol(mat)),seq_len(nrow(mat)),t(display),col=colorRampPalette(c('#f7fbff','#6baed6','#08306b'))(100),axes=FALSE,xlab='',ylab='',zlim=c(0,1),main='Chromosome density profiles | illustrative abundant candidates')
missing<-which(is.na(display),arr.ind=TRUE)
if(nrow(missing)>0) rect(missing[,2]-.5,missing[,1]-.5,missing[,2]+.5,missing[,1]+.5,col='gray85',border=NA)
axis(1,at=seq_len(ncol(mat)),labels=colnames(mat),las=2,cex.axis=.8);axis(2,at=seq_len(nrow(mat)),labels=rev(labels),las=2,cex.axis=.65);box()
mtext('Top 15 pooled-E>10 candidates by each family density, deduplicated; rows are not clustered.',side=3,line=.5,cex=.75)
mtext('Row-scaled union density: white = 0, dark blue = 1; gray = no annotated valid windows.',side=1,line=3,cex=.8)
dev.off()

d<-read('specificity_prevalence.tsv')
png(paste0(p,'03_specificity_and_recurrence.png'),width=2400,height=1100,res=180)
par(mfrow=c(1,2),mar=c(5,5,4,1),oma=c(3,0,1,0))
plot(d$prevalence_fraction*100,d$max_chromosome_count_fraction,pch=16,cex=.2,col=adjustcolor('#247BA0',alpha.f=.15),xlab='Haplotypes with target occurrence (%)',ylab='Largest chromosome count fraction',main='Prevalence versus chromosome concentration',ylim=c(0,1))
plot(d$max_chromosome_count_fraction,d$dominant_chromosome_recurrence,pch=16,cex=.2,col=adjustcolor('#268878',alpha.f=.15),xlab='Largest chromosome count fraction',ylab='Same dominant chromosome / informative haps',main='Cross-haplotype recurrence of chromosome preference',ylim=c(0,1))
mtext('Union counts; reproducible sample of up to 40,000 candidates. Tied dominant chromosomes are excluded from recurrence.',outer=TRUE,side=1,line=.5,cex=.8)
mtext('Informative hap: target present, pooled dominant chromosome measurable, and at least two chromosomes with valid target windows.',outer=TRUE,side=1,line=1.7,cex=.75)
dev.off()
