args<-commandArgs(trailingOnly=TRUE);root<-if(length(args))args[1] else 'step1';out<-file.path(root,'plots')
read<-function(name)read.delim(file.path(out,name))
s<-read('summary.tsv');v<-setNames(s$value,s$metric)
start<-function(name,w=2400,h=1800){png(file.path(out,name),width=w,height=h,res=180);par(family='sans',col.main='#172B4D',col.axis='#354052',col.lab='#354052')}
selected_e<-as.numeric(Sys.getenv('SAT_ASO_SELECTED_E','10'));pooled_min<-Sys.getenv('SAT_ASO_POOLED_MIN','10');hap_min<-Sys.getenv('SAT_ASO_HAP_MIN','500')
start('01_step1_discovery_and_enrichment.png');par(mfrow=c(2,2),mar=c(5,5,4,2),oma=c(4,0,4,0))
values<-as.numeric(v[c('distinct_target_kmers','preliminary_candidates','selected_candidates')]);x<-barplot(values,names.arg=c('Observed in target','Count-screened','Enriched candidates'),col=c('#718096','#267EAE','#268878'),log='y',ylim=c(1,max(values)*4),ylab='Distinct canonical 16-mers (log scale)',main='Discovery and selection',cex.names=.85);text(x,values,format(values,big.mark=','),pos=3,cex=.85)
values<-as.numeric(v[c('both','hap_only','pooled_only')]);x<-barplot(values,names.arg=c('Pooled + hap','Hap only','Pooled only'),col=c('#268878','#E59432','#267EAE'),ylim=c(0,max(values)*1.2),ylab='Selected canonical 16-mers',main='Selection routes');text(x,values,format(values,big.mark=','),pos=3,cex=.85)
d<-read('enrichment_histogram.tsv');plot(d$midpoint,d$count,type='h',lwd=3,col='#267EAE',ylab='Preliminary candidates',xlab='Pooled log2 enrichment',main='Pooled enrichment distribution');abline(v=selected_e,col='#C75857',lty=2,lwd=2);legend('topright',legend=paste0('Pooled E > ',selected_e),col='#C75857',lty=2,bty='n')
d<-read('density_scatter.tsv');plot(d[,1],d[,2],pch=16,cex=.3,col=ifelse(d$selected==1,adjustcolor('#268878',alpha.f=.25),adjustcolor('#718096',alpha.f=.1)),xlab='log10(background density + epsilon)',ylab='log10(target density + epsilon)',main='Target versus background density');abline(a=log10(2^selected_e),b=1,col='#C75857',lty=2,lwd=2);legend('topleft',legend=c('Selected','Not selected',paste0('E > ',selected_e)),col=c('#268878','#718096','#C75857'),pch=c(16,16,NA),lty=c(NA,NA,2),bty='n',cex=.85)
mtext('STEP 1 | Exact canonical 16-mer discovery',outer=TRUE,side=3,line=1.5,cex=1.5,font=2)
mtext('573 non-reference haplotypes; CHM13 evaluated separately. Epsilon = 1e-9.',outer=TRUE,side=3,line=.1,cex=.95)
mtext(paste0('Pooled: E > ',selected_e,' and count >= ',pooled_min,'. Hap: E > ',selected_e,' and count >= ',hap_min,' in at least one hap.'),outer=TRUE,side=1,line=1,cex=.85)
mtext('Background is outside existing HSat2/3 annotations on eligible chromosomes. Scatter is a reproducible sample of up to 50,000 k-mers.',outer=TRUE,side=1,line=2.3,cex=.8);dev.off()
start('02_step1_candidate_properties.png',2700,1150);par(mfrow=c(1,3),mar=c(5,5,4,1),oma=c(4,0,4,0))
d<-read('prevalence_histogram.tsv');plot(d$midpoint*100,d$count,type='h',lwd=10,col='#268878',xlab='Haplotypes with target occurrence (%)',ylab='Selected canonical 16-mers',main='Target prevalence',xlim=c(0,100))
d<-read('gc_histogram.tsv');plot(d$GC_percent,d$count,type='h',lwd=10,col='#267EAE',xlab='GC content (%)',ylab='Selected canonical 16-mers',main='Sequence composition',xlim=c(0,100))
d<-read('orientation_histogram.tsv');plot(d$midpoint,d$count,type='h',lwd=10,col='#E59432',xlab='Canonical-forward fraction in target',ylab='Selected canonical 16-mers',main='Pooled target orientation',xlim=c(0,1))
mtext('STEP 1 | Candidate properties',outer=TRUE,side=3,line=1.5,cex=1.5,font=2)
mtext('No prevalence, GC or complexity filter was applied.',outer=TRUE,side=3,line=.1,cex=.95)
mtext('Prevalence is conditional on available T2T-passed chromosomes. Orientation is relative to the filtered FASTA, not transcription.',outer=TRUE,side=1,line=1,cex=.85)
mtext('These are exact-match sequence candidates; mismatch, family/chromosome specificity and ASO efficacy are not evaluated here.',outer=TRUE,side=1,line=2.3,cex=.85);dev.off()
