d <- read.delim('step1/threshold_sweep/threshold_summary.tsv')
selected <- as.numeric(Sys.getenv('SAT_ASO_SELECTED_E', '10'))
pooled_min <- Sys.getenv('SAT_ASO_POOLED_MIN', '100')
hap_min <- Sys.getenv('SAT_ASO_HAP_MIN', '10')
draw_selected <- function() abline(v=selected,lty=2,col='gray50')
p <- subset(d,route=='pooled'); u <- subset(d,route=='union')
png('step1/threshold_sweep/threshold_sweep.png',width=2400,height=1800,res=180)
par(mfrow=c(2,2),mar=c(4.7,5,3,1),oma=c(3,0,3,0))
plot(p$E_strictly_greater_than,pmax(1,p$candidates),type='b',log='y',pch=16,col='#247BA0',xlab='Strict log2 enrichment threshold (E > x)',ylab='Candidates (log scale)',main='Candidate retention',ylim=range(pmax(1,c(p$candidates,u$candidates))))
lines(u$E_strictly_greater_than,pmax(1,u$candidates),type='b',pch=17,col='#E49A32')
draw_selected();legend('topright',c('Pooled','Pooled OR any hap'),col=c('#247BA0','#E49A32'),pch=c(16,17),lty=1,bty='n')
plot(p$E_strictly_greater_than,100*p$zero_background_candidates/pmax(1,p$candidates),type='b',pch=16,col='#247BA0',ylim=c(0,100),xlab='Strict log2 enrichment threshold',ylab='Zero-background candidates (%)',main='Background absence among pooled candidates');draw_selected()
plot(p$E_strictly_greater_than,100*p$median_prevalence_fraction,type='b',pch=16,col='#247BA0',ylim=c(0,100),xlab='Strict log2 enrichment threshold',ylab='Median target prevalence (%)',main='Target occurrence across 573 haplotypes')
lines(u$E_strictly_greater_than,100*u$median_prevalence_fraction,type='b',pch=17,col='#E49A32');draw_selected()
plot(p$E_strictly_greater_than,pmax(1,p$present_in_at_least_90pct_haps),type='b',pch=16,log='y',col='#247BA0',ylim=range(pmax(1,c(p$present_in_at_least_90pct_haps,u$locally_pass_in_at_least_90pct_haps))),xlab='Strict log2 enrichment threshold',ylab='Candidates (log scale)',main='Broad occurrence versus broad enrichment')
lines(u$E_strictly_greater_than,pmax(1,u$locally_pass_in_at_least_90pct_haps),type='b',pch=17,col='#268878')
legend('topright',c('Pooled pass + broad hap occurrence','Local pass in broad hap fraction'),col=c('#247BA0','#268878'),pch=c(16,17),lty=1,bty='n',cex=.75);draw_selected()
mtext('STEP 1 | Enrichment threshold sweep',outer=TRUE,side=3,line=1,font=2,cex=1.4)
mtext(paste0('Pooled target count >=',pooled_min,'; local target count >=',hap_min,'; epsilon=1e-9. CHM13 excluded.'),outer=TRUE,side=1,line=.5,cex=.85)
mtext('Background: outside existing HSat2/3 BED. Occurrence does not establish KD efficacy. Zero counts plotted at 1 on log axes.',outer=TRUE,side=1,line=1.7,cex=.75)
dev.off()
